// Exports contract ABIs into the web app as a TypeScript module.
const fs = require("fs");
const path = require("path");

const artifactsDir = path.join(__dirname, "..", "artifacts", "contracts");
const outFile = path.join(__dirname, "..", "..", "web", "src", "lib", "abi.ts");

const contracts = ["GoldToken", "HeroNFT", "BattleArena"];

let output = "// Auto-generated by contracts/scripts/export-abi.js — do not edit.\n\n";
for (const name of contracts) {
  const artifactPath = path.join(artifactsDir, `${name}.sol`, `${name}.json`);
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  output += `export const ${name[0].toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(
    artifact.abi,
    null,
    2
  )} as const;\n\n`;
}

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, output);
console.log(`Wrote ${outFile}`);
